# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_books_in_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='in_print',
            field=models.BooleanField(verbose_name=True),
        ),
    ]
